In [44]:
import os
import pandas as pd
pd.__version__

'3.0.4'

In [46]:
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
# reading data
filepath = os.path.join(os.path.abspath(".."), "data", "car_fuel_efficiency_2026.csv")
df = pd.read_csv(filepath)
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [9]:
df.shape

(10000, 11)

In [22]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [29]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [41]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [32]:
df.origin.unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [34]:
df.fuel_efficiency_mpg[df.origin == "Asia"].max()

np.float64(41.2)

In [40]:
df.horsepower.median()

np.float64(254.0)

In [64]:
df.horsepower.value_counts().idxmax()

np.float64(252.0)

In [86]:
df.horsepower = df.horsepower.fillna(df.horsepower.mode()[0])

In [87]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [89]:
df.horsepower.median()

np.float64(252.0)

In [90]:
df.horsepower.describe()

count    10000.000000
mean       254.231500
std         21.830757
min        171.000000
25%        241.000000
50%        252.000000
75%        268.000000
max        334.000000
Name: horsepower, dtype: float64

In [132]:
x = df[df.origin == "Asia"][["vehicle_weight", "model_year"]].head(7).to_numpy()
x.shape, x.T.shape

((7, 2), (2, 7))

In [131]:
xtx = x@x.T
xtx.shape

(7, 7)

In [124]:
import numpy as np
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
np.linalg.pinv(xtx).shape, y.shape

((7, 7), (7,))

In [133]:
x.T.shape

(2, 7)

In [137]:
w = (x.T@np.linalg.pinv(xtx))@y
w

array([0.13644777, 0.2327492 ])

In [138]:
w.sum()

np.float64(0.36919696904926363)